---
- name: Add public keys
  hosts: all
  gather_facts: no
  tasks:
    - name: Add authorized keys from github
      authorized_key:
        user: "root"
        state: present
        key: "https://github.com/galbitz.keys"
      become: true
