---
- name: Create ubuntu 22.04 server template
  hosts: all
  tasks:
    - name: Creating template
      ansible.builtin.script: ./createtemplate_remote.sh
      register: results
    - name: Debug value
      ansible.builtin.debug:
        var: results.stdout
