---
- name: Create ubuntu 20.04 server template
  hosts: all
  tasks:
  - name: Creating template
    script: ./createtemplate_remote.sh
    register: results
  - debug:
      var: results.stdout
