---
cloudflare_traefik_dns_token: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_TRAEFIK_DNS_TOKEN') }}"
silverbullet_user: "{{ lookup('ansible.builtin.env', 'SILVERBULLET_USER') }}"

pangolin_crowdsec_enroll_key: "{{ lookup('ansible.builtin.env', 'PANGOLIN_CROWDSEC_ENROLL_KEY') }}"
pangolin_cloudflare_token: "{{ lookup('ansible.builtin.env', 'PANGOLIN_CLOUDFLARE_TOKEN') }}"
pangolin_secret: "{{ lookup('ansible.builtin.env', 'PANGOLIN_SECRET') }}"
pangolin_crowdsec_lapikey: "{{ lookup('ansible.builtin.env', 'PANGOLIN_CROWDSEC_LAPIKEY') }}"

grafana_cloud_loki_token: "{{ lookup('ansible.builtin.env', 'GRAFANA_CLOUD_LOKI_TOKEN') }}"
grafana_cloud_prometheus_token: "{{ lookup('ansible.builtin.env', 'GRAFANA_CLOUD_PROMETHEUS_TOKEN') }}"
