---
grafana_cloud_loki_token: "{{ lookup('ansible.builtin.env', 'GRAFANA_CLOUD_LOKI_TOKEN') }}"
grafana_cloud_prometheus_token: "{{ lookup('ansible.builtin.env', 'GRAFANA_CLOUD_PROMETHEUS_TOKEN') }}"
