---
pangolin_cloudflare_token: "{{ lookup('ansible.builtin.env', 'PANGOLIN_CLOUDFLARE_TOKEN') }}"
pangolin_secret: "{{ lookup('ansible.builtin.env', 'PANGOLIN_SECRET') }}"

grafana_cloud_loki_token: "{{ lookup('ansible.builtin.env', 'GRAFANA_CLOUD_LOKI_TOKEN') }}"
grafana_cloud_prometheus_token: "{{ lookup('ansible.builtin.env', 'GRAFANA_CLOUD_PROMETHEUS_TOKEN') }}"
