---
ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
ansible_user: sysadmin

homelab_email: "{{ lookup('ansible.builtin.env', 'HOMELAB_EMAIL') }}"

security_notification_email: "{{ homelab_email }}"
mta_remotes: "{{ lookup('ansible.builtin.env', 'MTA_REMOTES') }}"
