#!/usr/bin/env bash
#MISE description="Apply terraform"
#MISE dir="{{config_root}}/terraform"

set -a
export TF_VAR_HOME_IP=$(curl -sS https://ifconfig.co)
# import secrets to env
source <(sops -d "{{config_root}}/main.secret.sops.env")
terraform apply -compact-warnings -auto-approve -input=false "$@"
