#!/usr/bin/env bash
#MISE description="Initialize terraform"
#MISE dir="{{config_root}}/terraform"

set -a
export TF_VAR_HOME_IP=$(curl -sS https://ifconfig.co)
# import secrets to env
terraform init -input=false
