---
file_backup_dir: "/opt/file_backup"
file_backup_destination:

file_backup_list_of_folders_to_backup: []

file_backup_schedule_minute: "*"
file_backup_schedule_hour: "*"
file_backup_schedule_day: "*"
file_backup_schedule_month: "*"
