---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
- name: Check pre req
  ansible.builtin.assert:
    that:
      - containers_guacamole_docker_root_dir | length > 0
      - containers_guacamole_main_domain | length > 0
    fail_msg: "variable is missing. Define it in global vars"

- name: Make sure that the docker folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: a+rw,g+rw,o+rw
  loop:
    - "{{ containers_guacamole_dir }}"
    - "{{ containers_guacamole_dir }}/guacamole"
  become: true

- name: Copy docker compose
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u+rwx,g+rx,o+rx
    force: true
  loop:
    - src: "compose.yaml.j2"
      dest: "{{ containers_guacamole_dir }}/compose.yaml"
    - src: "guacamole/guacamole.properties.j2"
      dest: "{{ containers_guacamole_dir }}/guacamole/guacamole.properties"
  become: true

- name: Docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ containers_guacamole_dir }}"
