---
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

compactor:
  working_directory: /etc/loki/data/compactor
  compaction_interval: 60m
  retention_enabled: true
  retention_delete_delay: 1m
  delete_request_store: filesystem

limits_config:
  retention_period: 672h

common:
  path_prefix: /etc/loki/data
  storage:
    filesystem:
      chunks_directory: /etc/loki/data/chunks
      rules_directory: /etc/loki/data/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-04-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093
