---
# find icons here: https://github.com/walkxcode/dashboard-icons
- Hypervisors:
    - Shadow:
        href: https://shadow.home.star4.dev:8006/
        icon: proxmox.png
    - Bee:
        href: https://bee.home.star4.dev:8006/
        icon: proxmox.png
- Services:
    - Home Assistant:
        href: https://ha.home.04a.ca/
        icon: home-assistant-alt.png
    - Remote connect:
        href: https://guacamole.home.04a.ca/
        icon: guacamole.png
    - Diskstation:
        href: https://diskstation.home.star4.dev:5001/
        icon: synology.png
    - Unifi wifi:
        href: https://unifi.ui.com/
        icon: unifi.png
    - Uptime Kuma:
        href: https://uptime.home.04a.ca/
        icon: uptime-kuma.png
    - Portainer:
        href: https://portainer.home.04a.ca/
        icon: portainer.png
    - Traefik:
        href: https://traefik.home.04a.ca/
        icon: traefik.png
    - Grafana:
        href: https://grafana.home.04a.ca/
        icon: grafana.png
    - NUT:
        href: https://nut.home.04a.ca/cgi-bin/nut/upsstats.cgi
        icon: ups.png
    - Switch:
        href: http://192.168.1.3/
        icon: mdi-switch
    - Netboot:
        href: http://192.168.1.17:3500/
        icon: netboot.png
