---
creation_rules:
  - path_regex: .*\.secret(\.sops)?\.yaml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
          - age1rmlyc7jr5a0eqtlz9gdr2lwlnz2r9gcfz3w2ah6jyk4a8uy47sasfyxdzj
  - path_regex: .*\.secret(\.sops)?\.env
    key_groups:
      - age:
          - age1rmlyc7jr5a0eqtlz9gdr2lwlnz2r9gcfz3w2ah6jyk4a8uy47sasfyxdzj
