---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  AGE_FILE: "{{.ROOT_DIR}}/age.key"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"

includes:
  ansible: .taskfiles/ansible/Taskfile.yaml
  flux: .taskfiles/flux/Taskfile.yaml
  bootstrap: .taskfiles/bootstrap/Taskfile.yaml
  talos: .taskfiles/talos/Taskfile.yaml
  sops: .taskfiles/sops/Taskfile.yaml
  kubespray: .taskfiles/kubespray/Taskfile.yaml
  tf: .taskfiles/terraform/Taskfile.yaml

tasks:
  default:
    desc: List all tasks
    silent: false
    cmd: task --list-all

  generate-graph:
    desc: Generate graph
    cmd: dot -Tpng ./doc/comm.dot -o ./doc/comm.png

  encrypt-secrets:
    desc: Encrypt secrets
    cmd: sops -e main.secret.env > main.secret.sops.env
