---
- name: Create docker folders
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: u+rwx,g+rwx,o+rxw
  loop:
    - "{{ valheim_dir }}"

- name: Copy docker compose
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ valheim_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: u+rwx,g+rwx,o+rxw
    force: true

- name: Docker-compose up
  ansible.builtin.command:
    cmd: "docker-compose up -d"
    chdir: "{{ valheim_dir }}"
  changed_when: false
