---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-04a-ca
  namespace: default
spec:
  secretName: traefik-wildcard-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.k.04a.ca"
  dnsNames:
    - "*.k.04a.ca"
    - "*.t.04a.ca"
