---
- name: Make sure that the docker folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: 0777
  loop:
    - "{{ remote_guacamole_dir }}"

- name: Copy docker compose
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ remote_guacamole_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u+rw,g+rw,o+rw
    force: true

- name: Docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ remote_guacamole_dir }}"
