---
dependencies:
  - role: geerlingguy.docker
    become: true
    vars:
      docker_daemon_options:
        log-driver: "journald" #journald for grafana alloy compatibility
      docker_users:
        - gabor
        - sysadmin
