---
dependencies:
  - role: geerlingguy.docker
    become: true
    vars:
      docker_daemon_options:
        log-opts:
          max-size: "30m"
          max-file: "3"
      docker_users:
        - gabor
        - sysadmin
