---
dependencies:
  - role: geerlingguy.docker
    become: true
    vars:
      docker_daemon_options:
        log-driver: "local" #local driver has log rotation enabled by default
      docker_users:
        - gabor
        - sysadmin
