---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
- name: Check pre req
  ansible.builtin.assert:
    that:
      - containers_docker_base_docker_root_dir | length > 0
    fail_msg: "docker_dir global variable might be empty"

- name: Dependencies
  ansible.builtin.include_tasks: docker-dependencies.yml

- name: Persistent storage
  ansible.builtin.include_tasks: persistent-storage.yml

# bug. sometimes it needs: pip install requests==2.31 to pin library
- name: Create shared network [proxy]
  community.docker.docker_network:
    name: "{{ containers_docker_base_network_name }}"
    state: present
    driver: bridge
  become: true
