---
ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
ansible_user: root

docker_users:
  - gabor

docker_dir: /opt/docker/data

docker_daemon_options:
  log-opts:
    max-size: "30m"
    max-file: "3"

security_notification_email: "gabor@gabor.one"
mta_remotes: "{{ lookup('ansible.builtin.env', 'MTA_REMOTES') }}"
