---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  init:
    desc: Initialize terraform
    cmds:
      - task: .execute
        vars:
          ARGS: "init -input=false"

  apply:
    desc: Apply terraform
    cmds:
      - task: .execute
        vars:
          ARGS: "apply -compact-warnings -auto-approve -input=false"

  plan:
    desc: Plan terraform
    cmds:
      - task: .execute
        vars:
          ARGS: "plan -compact-warnings -input=false"

  generate-inventory:
    desc: Generate ansible host inventory
    cmds:
      - task: .execute
        vars:
          ARGS: "apply -target=local_file.hosts -compact-warnings -auto-approve"

  run:
    desc: Run terraform. Add command as parameter eg. `task tf-run -- plan`
    cmds:
      - task: .execute
        vars:
          ARGS: "{{.CLI_ARGS}}"

  destroy:
    desc: Destroy terraform
    cmds:
      - task: .execute
        vars:
          ARGS: "destroy -compact-warnings"

  .execute:
    dir: "{{.DIR}}"
    internal: true
    vars:
      ARGS: "{{.ARGS}}"
      DIR: '{{ default "./terraform" .DIR }}'
    cmd: |
      set -a
      export TF_VAR_HOME_IP=`curl -sS https://ifconfig.co`
      # import secrets to env
      source <(sops -d {{.ROOT_DIR}}/main.secret.sops.env)
      terraform {{.ARGS}}
