---
- name: Copy dns update script
  ansible.builtin.template:
    src: cloudflare-dns-update.j2
    dest: "{{ docker_dir }}/cloudflare-dns-update.sh"
    mode: a+x
- name: Set up container to run cron
  community.docker.docker_container:
    name: cloudflare-dns
    image: alpine
    pull: true
    state: started
    restart_policy: always
    command: "crond -f -l 8"
    volumes: "{{ docker_dir }}/cloudflare-dns-update.sh:/etc/periodic/daily/cloudflare-dns-update.sh"
