---
# Idea from: https://docs.technotim.live/posts/grafana-loki/
# Docker parser: https://ruanbekker.medium.com/logging-with-docker-promtail-and-grafana-loki-d920fd790ca8

- name: Make sure that insight folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: u+rwx,g+rwx,o+rxw
  loop:
    - "{{ containers_insight_dir }}"
    - "{{ containers_insight_dir }}/prometheus-data"
    - "{{ containers_insight_dir }}/influx"
    - "{{ containers_insight_dir }}/influx/data"
    - "{{ containers_insight_dir }}/influx/config"
  become: true

- name: Copy docker compose for insight
  ansible.builtin.template:
    src: insight-compose.yml.j2
    dest: "{{ containers_insight_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: u+rwx,g+rwx,o+rxw
    force: true
  become: true

- name: Copy configs
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    owner: root
    group: root
    mode: u+rwx,g+rwx,o+rxw
    force: true
  loop:
    - src: "insight/"
      dest: "{{ containers_insight_dir }}"
  become: true

- name: Deploy Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ containers_insight_dir }}"
