---
# https://docs.technotim.live/posts/NUT-server-guide/

- name: Make sure that nut folder exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: u+rwx,g+rwx,o+rxw
  loop:
    - "{{ containers_nut_dir }}"
  become: true

- name: Copy docker compose for nut
  ansible.builtin.template:
    src: nut-compose.yml.j2
    dest: "{{ containers_nut_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u+rwx,g+rwx,o+rxw
    force: true

- name: Deploy Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ containers_nut_dir }}"
