---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
- name: Check pre req
  ansible.builtin.assert:
    that:
      - containers_notes_storage_docker_root_dir | length > 0
    fail_msg: "variable is missing. Define it in global vars"

- name: Ensuring folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: u+rwx,g+rwx,o+rxw
  loop:
    - "{{ containers_notes_storage_dir }}"
  become: true
