---
- name: Configure docker-server
  hosts: dockerserver
  tasks:
    - name: Update apt repos
      apt:
        update_cache: true
        upgrade: 'yes'
      changed_when: false
      become: true
  roles:
    - essentials
    - my_user
    - geerlingguy.docker
    - containers
