---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks

- name: Check pre req
  ansible.builtin.assert:
    that:
      - containers_portainer_docker_root_dir | length > 0
    fail_msg: "variable is missing. Define it in global vars"

- name: Make sure that portainer folder exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: u+rwx,g+rwx,o+rxw
  become: true
  loop:
    - "{{ containers_portainer_dir }}"
    - "{{ containers_portainer_dir }}/data"

- name: Copy docker compose for portainer
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "{{ containers_portainer_dir }}/compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u+rwx,g+rwx,o+rxw
    force: true

- name: Deploy Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ containers_portainer_dir }}"
