---
- name: Make sure that Jellyfin folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: u+rw,g+rw,o+rw
  loop:
    - "{{ jellyfin_dir }}"
    - "{{ jellyfin_config_dir }}"
    - "{{ jellyfin_cache_dir }}"
  become: true

- name: Copy docker compose for jellyfin
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "{{ jellyfin_dir }}/compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u+rw,g+rw,o+rw
    force: true
  become: true

- name: Deploy Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ jellyfin_dir }}"
