---
- name: Add repo using key from URL
  ansible.builtin.deb822_repository:
    name: 1password
    types: deb
    uris: https://downloads.1password.com/linux/debian/amd64
    suites: stable
    components: main
    architectures: amd64
    signed_by: https://downloads.1password.com/linux/keys/1password.asc
  become: true

- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: true
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  become: true

- name: Install 1Password
  ansible.builtin.apt:
    name:
      - 1password
      - 1password-cli
    state: present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  become: true
