---
- name: Install dwm build requirements
  ansible.builtin.package:
    name:
      - build-essential
      - git
      - make
      - libx11-dev
      - libxinerama-dev
      - libxft-dev
    state: present
  become: true

- name: Git checkout dwm
  ansible.builtin.git:
    repo: https://git.suckless.org/dwm
    dest: "{{ home }}/code/dwm"
    version: master # noqa: latest

- name: Copy file config
  ansible.builtin.copy:
    src: "{{ home }}/code/dwm/config.def.h"
    remote_src: true
    dest: "{{ home }}/code/dwm/config.h"
    mode: u+rw,g+r,o+r
    force: false

- name: Ensure term is set to kitty
  ansible.builtin.replace:
    path: "{{ home }}/code/dwm/config.h"
    regexp: '\"st\"'
    replace: '"kitty"'

- name: Install dwm
  community.general.make:
    chdir: "{{ home }}/code/dwm"
    target: install
  become: true

- name: Git checkout dmenu
  ansible.builtin.git:
    repo: https://git.suckless.org/dmenu
    dest: "{{ home }}/code/dmenu"
    version: master # noqa: latest

- name: Install dmenu
  community.general.make:
    chdir: "{{ home }}/code/dmenu"
    target: install
  become: true

- name: Copy xsession
  ansible.builtin.copy:
    src: .xsession
    dest: "{{ home }}/.xsession"
    owner: gabor
    mode: u+rw,g+rw,o+rw

- name: Create session file
  ansible.builtin.copy:
    src: dwm.desktop
    dest: "/usr/share/xsessions/dwm.desktop"
    owner: root
    mode: u+rw,g+r,o+r
  become: true
