---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-04a-ca
  namespace: default
spec:
  secretName: local-04a-ca-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.k.04a.ca"
  dnsNames:
    - "*.k.04a.ca"
