---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-pvc
  namespace: guacamole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
