---
- name: Set up cloudflare tunnel
  community.docker.docker_container:
    name: cloudflare-tunnel
    image: cloudflare/cloudflared:latest
    pull: true
    state: started
    restart_policy: always
    command: "tunnel --no-autoupdate run --loglevel error --token {{ cloudflare_tunnel_token }}"
