---
- name: Make sure that the docker folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
    mode: 0755
  loop:
    - "{{ docker_dir }}"
    - "{{ dashy_dir }}"
    - "{{ dashy_dir }}/public"
    - "{{ dashy_dir }}/icons"

- name: Copy dashy config
  ansible.builtin.copy:
    dest: "{{ dashy_dir }}/public/conf.yml"
    src: "dashy-config.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
    force: true
  register: containers_dashy_config_copy

- name: Clone icons
  ansible.builtin.git:
    repo: "https://github.com/walkxcode/dashboard-icons.git"
    dest: "{{ dashy_dir }}/icons/dashboard-icons"
    version: 997f8e2

- name: Set up dashy container
  community.docker.docker_container:
    name: dashy
    image: lissy93/dashy:latest
    pull: true
    state: started
    restart_policy: always
    volumes:
      - "{{ dashy_dir }}/public/conf.yml:/app/public/conf.yml"
      - "{{ dashy_dir }}/icons:/app/public/item-icons/icons"
    ports: "8295:80"
    recreate: "{{ containers_dashy_config_copy.changed }}"
