---
- name: Make sure that the docker folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: u+rwx,g+rwx,o+rxw
  loop:
    - "{{ dashy_dir }}"
    - "{{ dashy_dir }}/public"
    - "{{ dashy_dir }}/icons"

- name: Copy dashy config
  ansible.builtin.copy:
    dest: "{{ dashy_dir }}/public/conf.yml"
    src: "dashy-config.yml"
    owner: root
    group: root
    mode: u+rwx,g+rwx,o+rxw
    force: true
  register: containers_dashy_config_copy

- name: Clone icons
  ansible.builtin.git:
    repo: "https://github.com/walkxcode/dashboard-icons.git"
    dest: "{{ dashy_dir }}/icons/dashboard-icons"
    version: 997f8e2

- name: Set up dashy container
  community.docker.docker_container:
    name: dashy
    image: lissy93/dashy:latest
    pull: true
    state: started
    restart_policy: always
    volumes:
      - "{{ dashy_dir }}/public/conf.yml:/app/public/conf.yml"
      - "{{ dashy_dir }}/icons:/app/public/item-icons/icons"
    networks:
      - name: shared
    comparisons:
      networks: strict
    recreate: "{{ containers_dashy_config_copy.changed }}"
    labels:
      "traefik.enable": "true"
      "traefik.docker.network": "shared"
      "traefik.http.routers.dashy-http.entrypoints": "web"
      "traefik.http.routers.dashy-http.rule": "HostRegexp(`{host:dashboard\\..+}`)"
      "traefik.http.routers.dashy-https.entrypoints": "websecure"
      "traefik.http.routers.dashy-https.rule": "HostRegexp(`{host:dashboard\\..+}`)"
      "traefik.http.routers.dashy-https.tls": "true"
