---
- name: Make sure that Jellyfin mounting folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: u+rwx,g+rwx,o+rxw
  loop:
    - "{{ containers_jellyfin_config_dir }}"
    - "{{ containers_jellyfin_cache_dir }}"
- name: Make sure that Jellyfin media folder exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "root"
    group: "root"
    state: directory
    mode: u+rwx,g+rwx,o+rxw
  loop:
    - "{{ containers_jellyfin_mountpoint }}/music"
- name: Required packages
  ansible.builtin.package:
    name: cifs-utils
    state: present
- name: Mount network share
  ansible.posix.mount:
    src: "//{{ diskstation_jellyfin_ip }}/music"
    path: "{{ containers_jellyfin_mountpoint }}/music"
    fstype: cifs
    opts: "username={{ diskstation_jellyfin_username }},password={{ diskstation_jellyfin_password }}"
    state: mounted
- name: Jellyfin container
  community.docker.docker_container:
    name: jellyfin
    image: jellyfin/jellyfin:latest
    pull: true
    state: started
    restart_policy: always
    volumes:
      - "{{ containers_jellyfin_config_dir }}:/config"
      - "{{ containers_jellyfin_cache_dir }}:/cache"
      - "{{ containers_jellyfin_mountpoint }}:/media"
    networks:
      - name: shared
    comparisons:
      networks: strict
    labels:
      "traefik.enable": "true"
      "traefik.docker.network": "shared"
      "traefik.http.services.jellyfin.loadbalancer.server.port": "8096"
      "traefik.http.services.jellyfin.loadbalancer.server.scheme": "http"
      "traefik.http.routers.jellyfin-http.entrypoints": "web"
      "traefik.http.routers.jellyfin-http.rule": "HostRegexp(`{host:jellyfin\\..+}`,`{host:media\\..+}`)"
      "traefik.http.routers.jellyfin-https.entrypoints": "websecure"
      "traefik.http.routers.jellyfin-https.rule": "HostRegexp(`{host:jellyfin\\..+}`,`{host:media\\..+}`)"
      "traefik.http.routers.jellyfin-https.tls": "true"
