---
- name: Check pre req
  ansible.builtin.assert:
    that:
      - cloudflare_api_token is defined
      - cloudflare_tunnel_token is defined
      - cloudflare_email is defined
      - cloudflare_home_record_content is defined
      - cloudflare_zone_id is defined
      - cloudflare_home_record_id is defined
      - cloudflare_account_id is defined
      - cloudflare_ntfy_base_url is defined
    fail_msg: "tf_* variable usually defined in 'group_vars/tf_ansible_vars_file.yml' is missing"
- name: Cloudflare tunnel
  ansible.builtin.include_tasks: cloudflare-tunnel.yml
- name: Jellyfin
  ansible.builtin.include_tasks: jellyfin.yml
- name: Pi-hole
  ansible.builtin.include_tasks: pi-hole.yml
- name: Dashy
  ansible.builtin.include_tasks: dashy.yml
- name: Insight Composer stack
  ansible.builtin.include_tasks: insight.yml
- name: Nut
  ansible.builtin.include_tasks: nut.yml
