---
# https://docs.technotim.live/posts/NUT-server-guide/

- name: Run NUT container
  community.docker.docker_container:
    name: nut
    image: galbitz/nut:latest
    pull: true
    state: started
    restart_policy: always
    devices:
      - /dev/bus/usb/002/003
    ports:
      - 8082:80
      - 3493:3493
