---
# https://docs.technotim.live/posts/NUT-server-guide/

- name: Make sure that nut folder exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: u+rwx,g+rwx,o+rxw
  loop:
    - "{{ nut_dir }}"

- name: Copy docker compose for nut
  ansible.builtin.template:
    src: nut-compose.j2
    dest: "{{ nut_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: u+rwx,g+rwx,o+rxw
    force: true

- name: Deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: "{{ nut_dir }}"
