---
- name: Make sure that portainer folder exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
    mode: 0755
  loop:
    - "{{ portainer_dir }}"

- name: Copy docker compose for portainer
  ansible.builtin.template:
    src: portainer-compose.j2
    dest: "{{ portainer_dir }}/portainer-compose.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
    force: true

- name: Deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: "{{ portainer_dir }}"
