---
- name: Make sure that traefik compose folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: u+rwx,g+rwx,o+rxw
  loop:
    - "{{ traefik_dir }}"

- name: Copy docker compose for insight
  ansible.builtin.template:
    src: traefik.j2
    dest: "{{ traefik_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: u+rwx,g+rwx,o+rxw
    force: true

- name: Copy configs
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    owner: root
    group: root
    mode: u+rwx,g+rwx,o+rxw
    force: true
  loop:
    - src: "traefik/"
      dest: "{{ traefik_dir }}"

- name: Deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: "{{ traefik_dir }}"
