---
- name: Create watchtower container
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    state: started
    restart_policy: always
    command: "--cleanup --interval 3600"
