---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks

- name: Check pre req
  ansible.builtin.assert:
    that:
      - containers_authelia_docker_root_dir | length > 0
      - containers_traefik_main_domain is defined
      - containers_traefik_tunnel_domain is defined
      - homelab_email is defined
    fail_msg: "variable is missing. Define it in global vars"

- name: Make sure that the docker folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: u+rwx,g+rwx,o+rxw
  become: true
  loop:
    - "{{ containers_authelia_dir }}"
    - "{{ containers_authelia_dir }}/config"

- name: Copy files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u+rwx,g+rwx,o+rxw
    force: true
  become: true
  loop:
    - src: "compose.yaml.j2"
      dest: "{{ containers_authelia_dir }}/compose.yaml"
    - src: "config/configuration.yml.j2"
      dest: "{{ containers_authelia_dir }}/config/configuration.yml"
    - src: "config/users_database.yml.j2"
      dest: "{{ containers_authelia_dir }}/config/users_database.yml"

- name: Deploy docker compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ containers_authelia_dir }}"
