---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
- name: Check pre req
  ansible.builtin.assert:
    that:
      - containers_traefik_docker_root_dir | length > 0
      - containers_traefik_main_domain is defined
    fail_msg: "variable is missing. Define it in global vars"

- name: Traefik - Make sure that folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: u+rwx,g+rwx,o+rxw
  loop:
    - "{{ containers_traefik_dir }}"
    - "{{ containers_traefik_dir }}/config"
    - "{{ containers_traefik_dir }}/config/extra"

- name: Traefik - Copy config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u+rwx,g+rwx,o+rxw
    force: true
  loop:
    - src: "compose.yaml.j2"
      dest: "{{ containers_traefik_dir }}/compose.yaml"
    - src: config/traefik.yaml.j2
      dest: "{{ containers_traefik_dir }}/config/traefik.yaml"

- name: Traefik - Copy optional file
  ansible.builtin.template:
    src: "{{ containers_traefik_dynamic_conf }}"
    dest: "{{ containers_traefik_dir }}/config/extra/dynamic_conf.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u+rwx,g+rwx,o+rxw
    force: true
  when: containers_traefik_dynamic_conf is defined and containers_traefik_dynamic_conf | default('') | trim != ""

- name: Traefik - deploy docker compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ containers_traefik_dir }}"
