---
- name: Configure - Capture home directory
  ansible.builtin.set_fact:
    desktop_home: "{{ ansible_env.HOME }}"

- name: Configure - Set build directory
  ansible.builtin.set_fact:
    desktop_build_dir: "{{ desktop_home }}/build"
