---
- name: Make sure that the docker folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: 0777
  loop:
    - "{{ pihole_dir }}"
    - "{{ pihole_dir }}/etc-pihole"
    - "{{ pihole_dir }}/etc-dnsmasq.d"
  become: true

- name: Copy configs folders
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u+rwx,g+rwx,o+rxw
    force: true
  loop:
    - src: "./"
      dest: "{{ pihole_dir }}"
  become: true

- name: Copy docker compose
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ pihole_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u+rwx,g+rwx,o+rxw
    force: true

- name: Docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ pihole_dir }}"
