---
- name: Create user with ssh key
  user:
    name: '{{ username }}'
    state: present
    shell: /bin/bash
    password: '{{ password_hash }}'
    update_password: on_create
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
  become: true
- name: Add authorized keys from github
  authorized_key:
    user: '{{ username }}'
    state: present
    key: '{{ keyurl }}'
  become: true
- name: 'Add sudoers rules for {{ username }}'
  copy:
    dest: '/etc/sudoers.d/{{ username }}'
    content: |
        {{ username }} ALL=(ALL) NOPASSWD: ALL
    mode: 0440
    owner: root
    group: root
  become: true