---
- name: Install promtail
  ansible.builtin.import_role:
    name: patrickjahns.promtail
  vars:
    promtail_config_clients:
      - url: "http://192.168.1.17:3100/loki/api/v1/push"
        external_labels:
          host: "{{ ansible_hostname }}"
    promtail_config_positions:
      filename: "{{ promtail_positions_directory }}/positions.yaml"
      sync_period: "60s"

    promtail_config_scrape_configs:
      - job_name: journal
        journal:
          max_age: 12h
          labels:
            job: systemd-journal
        relabel_configs:
          - source_labels: ["__journal__systemd_unit"]
            target_label: "unit"
