---
- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: true

- name: Restart ssh (Redhat)
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  become: true
