---
containers_authelia_dir: "{{ docker_dir }}/authelia"

containers_authelia_session_secret: "{{ lookup('ansible.builtin.env', 'AUTHELIA_MY_SESSION_SECRET') }}"
containers_authelia_encryption_key: "{{ lookup('ansible.builtin.env', 'AUTHELIA_MY_STORAGE_ENCRYPTION_KEY') }}"
containers_authelia_jwt_secret: "{{ lookup('ansible.builtin.env', 'AUTHELIA_MY_JWT') }}"

containers_authelia_email: "{{ homelab_email }}"
