---
- name: Install promtail
  ansible.builtin.import_role:
    name: patrickjahns.promtail
  vars:
    promtail_user_additional_groups: "{{ logclient_additional_groups }}"
    promtail_config_clients:
      - url: "http://192.168.1.17:3100/loki/api/v1/push"
        external_labels:
          host: "{{ ansible_hostname }}"
    promtail_config_positions:
      filename: "{{ promtail_positions_directory }}/positions.yaml"
      sync_period: "60s"

    promtail_config_scrape_configs:
      - job_name: journal
        journal:
          max_age: 12h
          labels:
            job: systemd-journal
        relabel_configs:
          - source_labels: ["__journal__systemd_unit"]
            target_label: "unit"
    # this needs to be optional for nodes that don't have docker
    # - job_name: docker
    #   docker_sd_configs:
    #     - host: unix:///var/run/docker.sock
    #       refresh_interval: 5s
    #   relabel_configs:
    #     - source_labels: ["__meta_docker_container_name"]
    #       regex: "/(.*)"
    #       target_label: "container"
    #     - source_labels: ["__meta_docker_container_log_stream"]
    #       target_label: "logstream"
    #     - source_labels: ["__meta_docker_container_label_logging_jobname"]
    #       target_label: "job"
