---
- name: Make sure that the docker folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: a+rw,g+rw,o+r-w
  loop:
    - "{{ beszel_hub_dir }}"
    - "{{ beszel_hub_dir }}/beszel-hub/tailscale/config"
  become: true

- name: Copy docker compose
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "{{ beszel_hub_dir }}/compose.yaml"
    owner: root
    group: root
    mode: u+rw,g+rw,o+r-w
    force: true
  become: true

- name: Copy beszel hub config
  ansible.builtin.template:
    src: beszel-hub.json.j2
    dest: "{{ beszel_hub_dir }}/beszel-hub/tailscale/config/beszel-hub.json"
    owner: root
    group: root
    mode: u+rw,g+rw,o+r-w
    force: true
  become: true

- name: Docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ beszel_hub_dir }}"
