---
- name: Install Python and python3-pip
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
    state: present
  when: ansible_distribution != 'Alpine'

- name: Install docker module for Python
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose
  when: ansible_distribution != 'Alpine'
