---
- name: Make sure that the docker folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: 0777
  loop:
    - "{{ netboot_dir }}"
    - "{{ netboot_dir }}/assets"
    - "{{ netboot_dir }}/config"

- name: Copy docker compose
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ netboot_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: u+rwx,g+rwx,o+rxw
    force: true

- name: Docker-compose up
  ansible.builtin.command:
    cmd: "docker-compose up -d"
    chdir: "{{ netboot_dir }}"
  changed_when: false
