---
- name: Debian desktop
  hosts: xrdp
  vars:
    ansible_user: gabor
  roles:
    - star4.essentials.timezone
    - star4.essentials.autoupdate
    - role: geerlingguy.docker
      become: true
    - docker_shared
    - desktop
    - gantsign.visual-studio-code
