---
# Main docker node v2024-05-21-02
- name: Configure docker-server
  hosts: docker-server
  vars:
    file_backup_list_of_folders_to_backup:
      - "/opt/docker/data/insight/grafana"
      - "/opt/docker/data/insight/influx/data"
      - "/opt/docker/data/insight/prometheus-data"
      - "/opt/docker/data/jellyfin"
      - "/opt/docker/data/portainer/data"
      - "/opt/docker/data/quacamole"
      - "/opt/docker/data/uptime-kuma"
    file_backup_mount_dir: "/mnt/diskstation-proxmox-data"
    file_backup_nas_username: "{{ lookup('ansible.builtin.env', 'NAS_BACKUP_USERNAME') }}"
    file_backup_nas_password: "{{ lookup('ansible.builtin.env', 'NAS_BACKUP_PASSWORD') }}"
    file_backup_schedule_hour: "1"
    file_backup_schedule_minute: "0"
  roles:
    - star4.essentials.timezone
    - star4.essentials.autoupdate
    - star4.essentials.hardening
    - star4.essentials.forwardmta
    - geerlingguy.docker
    - docker_shared
    - docker_network
    - containers
    - monitor
    - remote
    - file_backup
    - netboot
    - tailscale
    - frpc_container
