---
# Main docker node v2024-05-21-02
- name: Configure docker-server
  hosts: docker-server
  vars:
    docker_dir: /opt/docker/data
    containers_traefik_main_domain: "home.04a.ca"
    containers_traefik_tunnel_domain: "tunnel.04a.ca"
    file_backup_list_of_folders_to_backup:
      - "/opt/docker/data/insight/grafana"
      - "/opt/docker/data/insight/influx/data"
      - "/opt/docker/data/insight/prometheus-data"
      - "/opt/docker/data/jellyfin"
      - "/opt/docker/data/portainer/data"
      - "/opt/docker/data/quacamole"
      - "/opt/docker/data/uptime-kuma"
      - "/opt/docker/data/beszel/beszel-hub"
    file_backup_destination: "/mnt/backup"
    file_backup_schedule_hour: "1"
    file_backup_schedule_minute: "0"
  roles:
    - star4.essentials.timezone
    - star4.essentials.autoupdate
    - star4.essentials.hardening
    - star4.essentials.forwardmta
    - role: containers/docker-base
    - role: containers/traefik
    - role: containers/authelia
    - role: containers/portainer
    - role: containers/cloudflare-dns
    - role: containers/cloudflare-tunnel
    - role: containers/grafana-stack
    - network-mounts
    - file_backup
    - containers/uptime-kuma
    - containers/guacamole
    - containers/netboot
    - tailscale
    - frpc_container
    - containers/beszel_hub
    - role: containers/nut-server
    - role: containers/qbittorrent
    - role: containers/jellyfin
    - role: containers/homepage
