---
- name: Configure gateway
  hosts: gateway
  roles:
    - role: linux-base
    - role: autoupdate
      vars:
        autoupdate_notification_email: "{{ homelab_email }}"
    - role: mta
      vars:
        mta_remotes: "{{ lookup('ansible.builtin.env', 'MTA_REMOTES') }}" # noqa: var-naming[no-role-prefix]
