---
- name: Configure gateway
  hosts: gateway
  vars:
    docker_dir: /opt/docker
  roles:
    - role: containers/docker-base
    - role: containers/pangolin_server
      vars:
        containers_pangolin_secret: "{{ lookup('ansible.builtin.env', 'PANGOLIN_SECRET') }}" # noqa: var-naming[no-role-prefix]
        containers_pangolin_cloudflare_token: "{{ lookup('ansible.builtin.env', 'PANGOLIN_CLOUDFLARE_TOKEN') }}" # noqa: var-naming[no-role-prefix]
    - role: containers/notes_storage
    - role: containers/syncthing
      vars:
        containers_syncthing_enable_traefik: false # noqa: var-naming[no-role-prefix]
        containers_syncthing_docker_network: "pangolin" # noqa: var-naming[no-role-prefix]
    - role: containers/silverbullet
      vars:
        containers_silverbullet_enable_traefik: false # noqa: var-naming[no-role-prefix]
        containers_silverbullet_docker_network: "pangolin" # noqa: var-naming[no-role-prefix]
