---
- name: Configure kiosk
  hosts: kiosk,kiosk2
  roles:
    - role: linux-auth
    - role: autoupdate
      vars:
        autoupdate_notification_email: "{{ homelab_email }}"
    - role: mta
      vars:
        mta_remotes: "{{ lookup('ansible.builtin.env', 'MTA_REMOTES') }}" # noqa: var-naming[no-role-prefix]
