---
- name: Configure pi
  hosts: pikvm
  tasks:
    - name: Update apt repos
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      changed_when: false
      become: true
  roles:
    - star4.essentials.timezone
    - star4.essentials.autoupdate
    - star4.essentials.myuser
    - star4.essentials.hardening
    - geerlingguy.docker
    - docker_shared
    - watchtower
    - monitor
