---
- name: Configure PVE node
  hosts: bee, shadow, shadow2, exit, shadow3
  vars:
    logclient_additional_groups: ["adm"]
  roles:
    - pve_default_config
    - prometheus.prometheus.node_exporter
    - logclient
