---
- name: Create OS cloudinit templates template
  hosts: game
  gather_facts: false
  tasks:
    - name: Create Ubuntu template
      ansible.builtin.script: ./files/create_ubuntu_template.sh
      register: results_ubuntu
      become: true
    - name: Debug value
      ansible.builtin.debug:
        var: results_ubuntu.stdout

    - name: Create Debian template
      ansible.builtin.script: ./files/create_debian_template.sh
      register: results_debian
      become: true
    - name: Debug value
      ansible.builtin.debug:
        var: results_debian.stdout
