---
- name: Configure services2 (new docker node)
  hosts: services2
  vars:
    docker_dir: /opt/docker
    containers_traefik_main_domain: "home.04a.ca"
    containers_traefik_secondary_domain: "tunnel.04a.ca"
    file_backup_list_of_folders_to_backup:
      - "/opt/docker/data/jellyfin"
      - "/opt/docker/data/portainer/data"
      - "/opt/docker/data/uptime-kuma"
      - "/opt/docker/data/beszel/beszel-hub"
    file_backup_destination: "/mnt/backup"
    file_backup_schedule_hour: "1"
    file_backup_schedule_minute: "0"
  roles:
    - role: linux-auth
    - role: autoupdate
      vars:
        autoupdate_notification_email: "{{ homelab_email }}"
    - role: mta
    - role: containers/docker-base
    - role: keepalived
      tags: ["keepalived"]
      vars:
        keepalived_vip: 192.168.1.18/24
        keepalived_interface: eth0
        keepalived_state: MASTER
    - role: containers/traefik
      vars:
        containers_traefik_dynamic_conf: templates/config/dynamic_conf.yaml.j2 # noqa: var-naming[no-role-prefix]
        containers_traefik_cloudflare_dns_token: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_TRAEFIK_DNS_TOKEN') }}" # noqa: var-naming[no-role-prefix]
    - role: containers/portainer
    - role: containers/grafana-stack
      vars:
        containers_grafana_stack_alloy_config: "{{ lookup('template', 'alloy/docker-server.config.alloy.j2') }}"
      tags: ["grafana-stack"]
    - role: network-mounts
      tags: ["network-mounts"]
    - role: file_backup
    - role: containers/uptime-kuma
      tags: ["uptime-kuma"]
    - role: containers/netboot
    - role: containers/beszel_hub
      vars:
        containers_beszel_hub_tailscale_oauth_token: "{{ lookup('ansible.builtin.env', 'TAILSCALE_BESZEL_TOKEN') }}"
    - role: containers/nut-server
    - role: containers/qbittorrent
    - role: containers/jellyfin
      tags: ["jellyfin"]
    - role: containers/homepage
      tags: ["homepage"]
    - role: containers/newt
      vars:
        containers_newt_id: "{{ lookup('ansible.builtin.env', 'PANGOLIN_NEWT_ID_DOCKER_SERVER') }}" # noqa: var-naming[no-role-prefix]
        containers_newt_secret: "{{ lookup  ('ansible.builtin.env', 'PANGOLIN_NEWT_SECRET_DOCKER_SERVER') }}" # noqa: var-naming[no-role-prefix]
      tags: ["newt"]
    - role: containers/beszel-agent
      vars:
        containers_beszel_agent_ssh_public_key: "{{ lookup('ansible.builtin.env', 'BESZEL_AGENT_SERVICES2') }}" # noqa: var-naming[no-role-prefix]
      tags: ["beszel-agent"]
    - role: containers/dozzle
      tags: ["dozzle"]
