---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
- name: Copy cloud init config
  ansible.builtin.copy:
    dest: "/etc/cloud/cloud.cfg.d/{{ item }}"
    src: "{{ item }}"
    owner: root
    group: root
    mode: u+rw
    force: true
  loop:
    - 99-disable-network-config.cfg
  become: true

- name: Remove netplan by cloud init
  ansible.builtin.file:
    path: "/etc/netplan/50-cloud-init.yaml"
    state: absent
  become: true

- name: Copy network configuration
  ansible.builtin.copy:
    dest: "/etc/systemd/network/{{ item }}"
    src: "{{ item }}"
    owner: root
    group: root
    mode: u+rw,g+r,o+r
    force: true
  loop:
    - container-shim.netdev
    - container-shim.network
    - enp6s18.network
  become: true

- name: Enable systemd-networkd
  ansible.builtin.systemd_service:
    state: restarted
    enabled: true
    daemon_reload: true
    name: systemd-networkd
  become: true

# might require reboot
- name: Create Docker MACVLAN network
  community.docker.docker_network:
    name: containernet
    driver: macvlan
    driver_options:
      parent: ens18
    ipam_config:
      - subnet: 192.168.1.0/24
        gateway: 192.168.1.1
        iprange: 192.168.1.64/29
        aux_addresses:
          host: 192.168.1.60
