---
# Idea from: https://docs.technotim.live/posts/grafana-loki/
# Docker parser: https://ruanbekker.medium.com/logging-with-docker-promtail-and-grafana-loki-d920fd790ca8
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
- name: Check pre req
  ansible.builtin.assert:
    that:
      - containers_grafana_stack_docker_root_dir | length > 0
    fail_msg: "variable is missing. Define it in global vars"

- name: Make sure that insight folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: u+rwx,g+rwx,o+rxw
  loop:
    - "{{ containers_grafana_stack_dir }}"
    - "{{ containers_grafana_stack_dir }}/prometheus-data"
    - "{{ containers_grafana_stack_dir }}/influx"
    - "{{ containers_grafana_stack_dir }}/influx/data"
    - "{{ containers_grafana_stack_dir }}/influx/config"
    - "{{ containers_grafana_stack_dir }}/loki"
    - "{{ containers_grafana_stack_dir }}/loki/data"
  become: true

- name: Copy docker compose for insight
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "{{ containers_grafana_stack_dir }}/compose.yaml"
    owner: root
    group: root
    mode: u+rwx,g+rwx,o+rxw
    force: true
  become: true

- name: Copy configs
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    owner: root
    group: root
    mode: u+rwx,g+rwx,o+rxw
    force: true
  loop:
    - src: "insight/"
      dest: "{{ containers_grafana_stack_dir }}"
  become: true

- name: Deploy Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ containers_grafana_stack_dir }}"
