---
containers_guacamole_docker_root_dir: "{{ docker_dir }}"
containers_guacamole_dir: "{{ containers_guacamole_docker_root_dir }}/guacamole"

# OIDC auth

# containers_guacamole_main_domain: "{{ containers_traefik_tunnel_domain }}"
containers_guacamole_auth_host: auth
containers_guacamole_guacamole_host: access

containers_guacamole_issuer: "https://{{ containers_guacamole_auth_host }}.{{ containers_guacamole_main_domain }}"
containers_guacamole_jwks_endpoint: "{{ containers_guacamole_issuer }}/jwks.json"
containers_guacamole_authorization_endpoint: "{{ containers_guacamole_issuer }}/api/oidc/authorization?state=1234abcedfdhf"
containers_guacamole_redirect_uri: "https://{{ containers_guacamole_guacamole_host }}.{{ containers_guacamole_main_domain }}"

containers_guacamole_extensions: "auth-sso-openid"
