serverAddr = "wormhole.star4.dev"
serverPort = 7000
#webServer.addr = "192.168.1.4"
#webServer.port = 7400
#webServer.user = "admin"
#webServer.password = "admin"
auth.token = "password"

[[proxies]]
name = "access"
type = "https"
#localIP = "192.168.1.17"
#localPort = 443
#remotePort = 443
customDomains = ["access.tunnel.04a.ca"]
[proxies.plugin]
type = "https2https"
localAddr = "192.168.1.17:443"
crtPath = "/home/gabor/.acme.sh/*.tunnel.04a.ca_ecc/fullchain.cer"
keyPath = "/home/gabor/.acme.sh/*.tunnel.04a.ca_ecc/*.tunnel.04a.ca.key"
hostHeaderRewrite = "guacamole.home.04a.ca"


[[proxies]]
name = "ha"
type = "https"
#localIP = "192.168.1.17"
#localPort = 443
#remotePort = 443
customDomains = ["ha.tunnel.04a.ca"]
[proxies.plugin]
type = "https2https"
localAddr = "192.168.1.17:443"
crtPath = "/home/gabor/.acme.sh/*.tunnel.04a.ca_ecc/fullchain.cer"
keyPath = "/home/gabor/.acme.sh/*.tunnel.04a.ca_ecc/*.tunnel.04a.ca.key"
hostHeaderRewrite = "ha.home.04a.ca"