---
- name: Restart resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
  become: true

- name: restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
  become: true
