---
- name: Configure docker-server2
  hosts: docker-server2
  roles:
    - star4.essentials.timezone
    - star4.essentials.autoupdate
    - star4.essentials.myuser
    - star4.essentials.hardening
    - star4.essentials.forwardmta
    - geerlingguy.docker
    - docker_shared
    - watchtower
    - monitor
    - remote
