---
# thin - simple jumpbox with debian
- name: Configure thin
  hosts: thin
  vars:
    frp_type: client
  roles:
    - star4.essentials.timezone
    - star4.essentials.autoupdate
    - star4.essentials.myuser
    - star4.essentials.hardening
    - star4.essentials.forwardmta
    - geerlingguy.docker
    - docker_shared
    - logclient
    - pihole
    - frp
