---
containers_jellyfin_mountpoint: "/media/jellyfin"
containers_jellyfin_config_dir: "{{ docker_dir }}/jellyfin/config"
containers_jellyfin_cache_dir: "{{ docker_dir }}/jellyfin/cache"

containers_homepage_dir: "{{ docker_dir }}/homepage"

containers_containers_insight_dir: "{{ docker_dir }}/insight"

containers_nut_dir: "{{ docker_dir }}/nut"

containers_portainer_dir: "{{ docker_dir }}/portainer"

containers_traefik_dir: "{{ docker_dir }}/traefik"
containers_traefik_main_domain: "home.04a.ca"
