---
ntfy_etc_dir: "{{ docker_dir }}/ntfy/etc"
ntfy_data_dir: "{{ docker_dir }}/ntfy/data"

jellyfin_mountpoint: "/media/jellyfin"
jellyfin_config_dir: "{{ docker_dir }}/jellyfin/config"
jellyfin_cache_dir: "{{ docker_dir }}/jellyfin/cache"

uptime_kuma_dir: "{{ docker_dir }}/uptime-kuma"
homer_dir: "{{ docker_dir }}/homer"

dashy_dir: "{{ docker_dir }}/dashy"

insight_dir: "{{ docker_dir }}/insight"
