---
containers_traefik_docker_root_dir: "{{ docker_dir }}"
containers_traefik_dir: "{{ containers_traefik_docker_root_dir }}/traefik"
containers_traefik_main_domain:
containers_traefik_secondary_domain: ""

containers_traefik_dynamic_conf: ""

containers_traefik_cloudflare_dns_token: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_TRAEFIK_DNS_TOKEN') }}"

containers_traefik_api: true
containers_traefik_dashboard: true
