---
name: Test workflow
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
      - run: ./decrypt.sh
      - run: cat unencrypted_secrets.sh | grep TF_VAR_HOME_ZONE
